### ISSUE TITLE
CLIP metrics error when prompts are longer than 77 tokens

### ISSUE THREAD

**Issue by segalinc** [stellar-gen-ai/stellar-metrics#1]
Hi, thanks for the contribution
I am trying the library and running into an issue as my data has prompts longer than 77 tokens

I would recommend to add some security check or add some truncation to the code to avoid the issue

**Comment by fostiropoulos** [comment]
Thank you for reporting the issue. Fixed by https://github.com/stellar-gen-ai/stellar-metrics/pull/2
